# Generated by Django 2.2.16 on 2022-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20220222_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reyting',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
